= {lab_name}


Welcome to the *Showcase "Lab"*, which is not a lab at all, but rather a showcase for what we can do both with the Showroom role, and also with Asciidoc, and in particular via the use of the integrated Antora toolchain.
In the following modules, we will show how to:

* Setup your `showroom` vars
** Configure Showroom to actually deploy your lab, workshop, or demo
* Extend your lab with additional services
** Web-based Terminal windows (ssh, bash, etc)
** Iframe windows (for web-based apps, etc)
** Consoles (OpenShift, Ansible Automation Controller, etc)
** Web-based IDEs (Visual Studio Code, Jupyter Labs, etc)
* Work with Antora and the pre-built Showroom Content Templates

| NOTE: Some services are not available yet but creating new Services will be covered and your labs etc can also reference consoles and services that open in *other* browser tabs eg for non-iFrame friendly content,

Throughout the rest of these modules we will refer to your content as "your lab" in this document, though it can equally be a workshop, demo, or anything else you want to deploy via Showroom.

[#getting-started]
== Getting started

The first thing you need to do is to set up your `showroom` vars, and create your repo. This module covers deploying a showroom-based lab to a VM or instance, typically a `bastion` host, but it could be any VM or instance that you have access to.

The first thing you need to do is to set up your `showroom` vars, and create your repo. This module covers deploying a showroom based lab to a VM or instance, typically a `bastion` host, but it could be any VM or instance that you have access to.

=== Showroom Lab Templates

The Showroom Lab Templates are a set of pre-built templates that you can use to quickly get started with your lab, workshop, or demo. They are designed to be used with the Showroom role, and are built using Antora, which is a static site generator for creating documentation sites from AsciiDoc content.

* link:https://github.com/rhpds/showroom_template_default.git[Default Showroom Template]
* link:https://github.com/rhpds/showroom_theme_rh1.git[RH 1 Showroom Template]
* link:https://github.com/rhpds/showroom_template_zero.git[Project Zero Showroom]